Drawing database scheme
iLeonidze/ncedu-food-delivery pull request #1
Opened 2021-10-27 16:39 UTC by grey3228

Первый полный вариант схемы базы данных проекта.

2021-10-28 11:52 UTC, swenkal commented
### USER

- @iLeonidze  прошу меня поправить, но postgreSQL не нравится, когда названия таблицы совпадает с какими-то зарезервированными словами, имя для таблицы "USER" будет допустимо? Поэтому нужно, наверное, исправить на USR. 
- **user_id** не нашел ничего про "CONSTANT";
- **reg_date**  : не нашел никакой сущности типа "CONSTANT", видимо необходимо сделать триггер на UPDATE и проверять поле reg_date;
- **full_name** : исходя из задания, как я понял могут быть "анонимы", то есть ФИО будет необязательно. Следовательно убрать NOT NULL и поставить DEFAULT "Аноним", как вариант;
- **email** : я бы добавил еще UNIQUE, так как будет странно, что одна почта для 2 аккаунтов;
- **last_signin_date** : не может быть "CONTSTANT",  так как будет изменяться после каждого выхода из приложения. Думаю, что поле все-таки может быть NULL, так как он может зарегаться, но ни разу не войти;
- **avatar_uuid** : по заданию может быть NULL (оно и логично), также нужно дописать ограничение ON DELETE SET NULL, чтобы при удалении картинки в строке пользователя проставлялся NULL.

###  Пример по полям
name table - USR
PK user_id BIGSERIAL 
full_name VARCHAR(50) DEFAULT "Аноним"
email VARCHAR(50) NOT NULL UNIQUE CHECK (email != '')
reg_date TIMESTAMP NOT NULL + TRIGGER user_update_reg_date
last_signin_date TIMESTAMP
avatar_uuid UUID REFERENCES picture (uuid) ON DELETE SET NULL

2021-10-28 12:20 UTC, swenkal commented
### COURIER

- **courier_id** : добавить к FK ON DELETE CASCADE, чтобы при удалении записи в USR удалялась сразу же запись из COURIER;
- **binded_warehouse_id** : я бы сократил название без приставки "binded". Также по заданию у курьера может и не быть прикрепленного склада сейчас. + добавить ON DELETE SET NULL;
- **phone_number** : добавить уникальность и проверку на пустую строку;
- **address** : если честно, то не понимаю зачем это нужно у курьера? что тут должно храниться? мне кажется нужно обсудить, если просто какой-то постоянный адрес, или это текущая локация? пока смотрю я на это, я бы удалил данное поле. @grey3228  @iLeonidze  что думаете?
- **current_balance** : увидел в postgres есть тип MONEY, может его для всех денежных колонок будем юзать? @grey3228
- **rating** : может использовать NUMERIC(3,2)?. Рейтинг обычно от 0.00 до 5.00, также поставим CHECK на больше 0 и меньше 5.00. @grey3228 @iLeonidze 

### Пример (без адреса)
courier_id BIGSERIAL PRIMARY KEY REFERENCES usr (user_id) ON DELETE  CASCADE
warehouse_id BIGSERIAL REFERENCES warehouse (warehouse_id) ON DELETE SET NULL
phone_number VARCHAR(20) NOT NULL UNIQUE CHECK (phone_number != '')
payment_data JSON
current_balance MONEY
rating NUMERIC(3, 2) CHECK (rating >= 0.00 AND rating =< 5.00)

2021-10-28 12:23 UTC, swenkal commented
### CLIENT
по аналогии с COURIER

### Пример
client_id BIGSERIAL PRIMARY KEY REFERENCES usr (user_id) ON DELETE CASCADE
payment_data JSON
phone_number VARCHAR(20) NOT NULL UNIQUE CHECK (phone_number != '')
rating NUMERIC(3,2) CHECK (rating >= 0.00 AND rating =< 5.00)

2021-10-28 12:26 UTC, swenkal commented
### MODERATOR
по аналогии с COURIER

### Пример
moderator_id BIGSERIAL PRIMARY KEY REFERENCES usr (user_id) ON DELETE CASCADE
warehouse_id BIGSERIAL REFERENCES warehouse (warehouse_id) ON DELETE SET NULL

2021-10-28 12:49 UTC, swenkal commented
### DELIVERY_SESSION

- **courier_id** : добавить каскадное удаление на FK;
- **orders_completed** : насколько я понял тип SERIAL, то он сюда не подходит. Ведь SERIAL создаёт последовательность не для конкретной строки и столбца, а для всей таблицы, поэтому может выйти конфуз. Видимо лучше юзать INT и CHECK;
- **money_earned**  : продолжаю предлагать использовать тип MONEY;

### Пример
delivery_session_id BIGSERIAL PRIMARY KEY
courier_id BIGSERIAL REFERENCES courier (courier_id) ON DELETE CASCADE
start_time TIMESTAMP NOT NULL
end_time TIMESTAMP
orders_completed SMALLINT DEFAULT 0 CHECK(orders_completed >= 0)
avg_time_per_order FLOAT4
money_earned MONEY DEFAULT 0

2021-10-28 13:03 UTC, swenkal commented
### PICTURE

- **owner** : добавить приставку id. Плюсом, я подумал, может он все-таки может быть NULL? ведь если мы загружаем картинки для товаров,  то загружает их допустим модератор склада. Потом его увольняют, т.е. удаляют информацию о нем. В таком случае при удалении нам надо удалить все картинки, где он является owner? Я к тому, что может быть у картинок товара может не быть владельца? Как думаете? @grey3228 @iLeonidze 
- **size**  : про тип SERIAL говорил в DELIVERY_SESSION, поэтому более подходящий тип INT (ИМХО)
- **download_date** :  мне кажется все-таки уместнее тогда "upload_date", имеется ведь ввиду дата загрузки, а не скачивания

###  Пример
uuid UUID PRIMARY KEY
owner_id BIGSERIAL REFERENCES usr (user_id) ON DELETE SET NULL
type IMAGE_TYPE (ENUM: "png", "jpeg") NOT NULL
size INT NOT NULL CHECK(size >= 0)
upload_date TIMESTAMP NOT NULL

2021-10-28 13:07 UTC, swenkal commented
###  CHAT

- **user_id** - каскадное удаление на FK;

###  Пример
chat_id BIGSERIAL PRIMARY KEY
user_id BIGSERIAL REFERENCES usr (user_id) ON DELETE CASCADE
date TIMESTAMP NOT NULL

2021-10-28 13:11 UTC, grey3228 commented
Не пугайтесь моих переоткрытий pr, эт я по неопытности :/

2021-10-28 13:35 UTC, swenkal commented
### CHAT_MESSAGE

-  я бы упростил имя таблицы до MESSAGE, но это вкусовщина, давайте решать.
- **chat_id** - каскадное удаление на FK;
- CHECK на message и picture_uuid предлагаю вынести один раз на уровень таблицы, чтобы не писать два раза одно и тоже 
- **date** - по CONTSTANT уже говорил выше, может быть только поставить триггер на UPDATE 
- нам видимо нужен еще триггер на такой кейс: в сообщении нет текста, только картинка. При удалении картинки в таблице picture, нам по-хорошему нужно будет удалить ID в таблице chat_message, но если мы это сделаем, то у нас оба поля message_text и pucture_uuid будут NULL. следовательно нам нужно будет это как-то отслеживать и удалять. @grey3228 

### Пример
name table MESSAGE
message_id BIGSERIAL PRIMARY KEY
replier_id BIGSERIAL
chat_id BIGSERIAL NOT NULL REFERENCES chat (chat_id) ON DELETE CASCADE
date TIMESTAMP NOT NULL + TRIGGER msg_date_update_trigger
message_text VARCHAR(200)
picture_uuid UUID REFERENCES picture (uuid) ON DELETE SET NULL
has_been_read BOOLEAN NOT NULL DEFAULT FALSE
CONSTRAINT text_or_picture_notnull CHECK (
(message_text IS NOT NULL AND message_text != '')
OR (picture_uuid IS NOT NULL) )
+ TRIGGER ON UPDATE picture_and_text_null

2021-10-28 13:56 UTC, swenkal commented
### PRODUCT

- **picture_uuid** :  мне кажется может быть NULL + добавить директиву ON DELETE SET NULL
- **description** :  мне кажется может быть NULL
- **weight** : по заданию INT (вес в граммах)
- **expiration_days** : по поводу SERIAL говорил выше, мне кажется здесь д.б. SMALLINT 
-  **in_showcase** : добавить DEFAULT FALSE
- **price** :  тип MONEY
- **discount** : может быть тоже в деньгах? тогда тип MONEY 

### Пример
product_id BIGSERIAL PRIMARY KEY
name VARCHAR(50) NOT NULL
description  VARCHAR(100) 
picture_uuid UUID REFERENCES picture (uuid) ON DELETE SET NULL
weight INT NOT NULL
composition VARCHAR(250)
expiration_days SMALLINT NOT NULL
in_showcase BOOLEAN DEFAULT FALSE
price MONEY NOT NULL
discount MONEY DEFAULT 0

2021-10-28 14:22 UTC, swenkal commented
### PRODUCT_POSITION

- **product_id** + **warehouse_id** : добавить каскадное удаление по FK;
- **current_amount** + **supply_amount** : тип д.б. INT (ИМХО)
- подумал о том, что у нас нет нигде информации об именно дате изготовления, ведь дата поставки это не одно и тоже, что дата изготовления. как думаете? @grey3228 @iLeonidze. 
- supplier_check : тип MONEY 

### Пример
product_position_id BIGSERIAL PRIMARY KEY
product_id BIGSERIAL REFERENCES product (product_id) ON DELETE CASCADE
warehouse_id BIGSERIAL REFERENCES warehouse (warehouse_id) ON DELETE CASCADE
current_amount INT NOT NULL CHECK(current_amount >= 0)
supply_amount INT NOT NULL
supply_date DATE NOT NULL
manufacture_date NOT NULL
supplier_check MONEY NOT NULL
supplier_name VARCHAR(30)
is_check_paid BOOLEAN DEFAULT FALSE

2021-10-28 14:32 UTC, swenkal commented
### WAREHOUSE 

- **geo** : я наткнулся в Postgre на тип данных POINT, разве не прекрасный кандидат для данной колонки? 
- **name** : я бы сделал его еще UNIQUE;
- **delivery_zone_coordinates** - здесь тоже есть идея. Нашел такой тип как Circle (x, y, r) хранит круг по сути точка + радиус. Может так будет легче работать? А можем просто вынести радиус в отдельное поле и тогда рассчитывать область действия или попадание точки(адреса клиента) в круг. @grey3228 @iLeonidze 

### Пример 
warehouse_id BIGSERIAL PRIMARY KEY
geo POINT NOT NULL
address VARCHAR(50) NOT NULL
name VARCHAR(50) NOT NULL UNIQUE
delivery_zone CIRCLE NOT NULL или delivery_radius INT NOT NULL

2021-10-28 14:55 UTC, swenkal commented
### PROMO_CODE

- **overall_to_activate** : тип INT с проверкой больше нуля, также я бы переименовал в limit_amount
- **currently_activated** : тип INT с проверкой больше нуля и дефолтным значением, также я бы переименовал в "current_amount"
- **text** : я бы переименовал в  "activation_phrase",  также она должна быть уникальной
- **sale_rubles** : тип MONEY 
-  **sale_percent** : проверка на больше 0 меньше 100
-  **user_id** : добавить каскадное удаление, ведь если юзера, персонально для которого выпущена скидка уже нет, то зачем нам эта запись тогда? 
- distributor_id : тут сложнее, я бы поставил все-таки возможность NULL значения и SET NULL при удалении
-  CHECK  для  sale_percent и sale_rubles вроде как можно упростить 
- на встрече обсуждали о добавлении поля desription

### Пример 
promo_code_id BIGSERIAL PRIMARY KEY
distributor_id BIGSERIAL REFERENCES usr (user_id) ON DELETE SET NULL
creation_date TIMESTAMP NOT NULL
activation_phrase VARCHAR(200) NOT NULL UNIQUE
is_active BOOLEAN DEFAULT TRUE
date_start TIMESTAMP
date_end TIMESTAMP
limit_amount INT CHECK(limit_amount>0)
current_amount INT CHECK(current_amount =< limit_amount AND current_amount >= 0) DEFAULT 0
sale_rubles MONEY
sale_percent FLOAT4 CHECK(sale_percent > 0 AND sale_percent < 100)
user_id BIGSERIAL REFERENCES usr (user_id) ON DELETE CASCADE
is_first_order BOOLEAN DEFAULT FALSE 
description TEXT
CONSTRAINT rubles_or_percent_sale_notnull CHECK (
(sale_rubles IS NOT NULL AND sale_rubles > 0) 
OR
(sale_percent IS NOT NULL) )

2021-10-28 15:16 UTC, swenkal commented
### ORDER

- **user_id** : каскадное удаление на FK;
- **coordinates** : я бы также переименовал бы в geo и сделал бы тип POINT;
- **binded_warehouse_id** : сократил бы название;
- **courier_id** : добавил бы ON DELETE SET NULL;
- **date_end** : все таки может быть NULL, заказ то не сразу завершается 
- **overall_price** : тип MONEY +  я не понял это стоимость уже с учетом всех скидок и надбавок за повышенный спрос?? @iLeonidze 
- **sale** : тип MONEY;
- **high_demand_coefficient** : чуть сократил бы хвост названия колонки + сделал бы NUMERIC(3,2) с CHECK
- **client_rating** + **delivery_rating** : тип NUMERIC(3,2) + проверка как в COURIER

###  Пример
order_id BIGSERIAL PRIMARY KEY
user_id BIGSERIAL REFERENCES usr (user_id) ON DELETE CASCADE
address VARCHAR(100) NOT NULL
geo POINT NOT NULL
warehouse_id BIGSERIAL NOT NULL REFERENCES warehouse(warehouse_id)
courier_id BIGSERIAL REFERENCES courier (courier_id) ON DELETE SET NULL
status ORDER_STATUS (ENUM ... ) NOT NULL DEFAULT "created"
date_start TIMESTAMP NOT NULL
date_end TIMESTAMP CHECK(date_end > date_start)
overall_price MONEY NOT NULL
high_demand_coeff NUMERIC(3,2) CHECK(high_demand_coeff >= 1 AND high_demand_coeff < 3) NOT NULL DEFAULT 1
sale MONEY NOT NULL DEFAULt 0 
promo_code_id BIGSERIAL REFERENCES promo_code (promo_code_id)
client_rating NUMERIC(3,2) CHECK (client_rating >= 0.00 AND client_rating =< 5.00)
delivery_rating NUMERIC(3,2) CHECK (delivery_rating >= 0.00 AND delivery_rating =< 5.00)

2021-10-28 15:24 UTC, swenkal commented
### ORDER_PRODUCT_POSITION

- order_id : добавить каскадное удаление на FK;
- amount : тип  INT с проверкой на 0 
- price :   тип MONEY 
- у меня еще один момент не складывается, а что делать с продуктами, когда заказ отменен? мы что в product_position должны как-то добавить текущее количество товаров? как вообще на уровне БД понять что с теми товарами делается, заказ на которые отменили? @grey3228 @iLeonidze  

### Пример
order_product_position_id BIGSERIAL PRIMARY KEY
order_id BIGSERIAL NOT NULL REFERENCES order (order_id) ON DELETE CASCADE
product_position_id BIGSERIAL  NOT NULL REFERENCES product_position (product_position_id)
amount INT NOT NULL CHECK(amount > 0)
price MONEY NOT NULL CHECK(price > 0)

2021-10-28 16:35 UTC, grey3228 commented
Исправил многие ошибки в последнем коммите. Тем не менее, ещё есть вопросы (@swenkal и мои личные):
1. Что мы храним в адресе курьера и нужен ли он?
2. Будет ли ок, если дефолтный рейтинг у курьера или клиента будет равным NULL? Например, клиент не выставляет оценку курьеру и/или наоборот.
3. Добавил триггеры в message на text и picture_uuid. Тут не знаю, как будет лучше, поскольку за триггеры пока вообще не шарю, поэтому поправьте.
4. Добавить ли в product_position дату изготовления?
5. Как храним географические координаты? Через FLOAT8[ ] или через геометрические типы: POINT для координат заказа и склада, CIRCLE для зоны доставки от склада?
6. Как быть с товарами в отменённом заказе?
Моя идея по поводу вопроса @swenkal об отменённом заказе и связанных товарах, если я правильно его понял: заказ отменяется, переводится в статус "cancelled", далее, по идее, срабатывает триггер, который все ассоциированные с заказом product_position'ы из order_product_position возвращает обратно в отменённом количестве в поле current_amount в таблицу product_position (опять же, я хз, может ли триггер такое провернуть, объясните, плз).  
upd: посмотрел документацию, по идее, можно сделать цепочку триггеров по апдейту на конкретных столбцах таблиц "order -> order_product_position -> product_position".

2021-10-29 15:49 UTC, iLeonidze commented
Посмотри на дифф - у тебя там стирается README и .gitignore, чего быть не должно, так как при мердже это сломает мейн. Наверное, надо ребейз сделать или ревертнуть изменения, которые стирают эти файлы

2021-10-29 16:31 UTC, iLeonidze requested changes
Вот что стоит исправить:
- У usr DEFAULT "Аноним" мне совсем не нравится, так как в системе совсем невозможна ситуация когда у пользователя нет имени. Либо у него есть имя, либо его самого нет, и база выкинет ошибку при создании такого невалидного аккаунта.
- Давайте предусмотрим удаление склада, а также его "деактивацию". Удаление нужно когда его завели по ошибке, но предусмотрим все каскадные удаления, а деактивация на случай когда склад действительно закрылся и его не нужно поддерживать в системе, но сохранить все связи со старыми данными нужно
- sale лучше переименовать в discount
- у price нет чека на позитивность числа. Рискуем по ошибке начислять деньги вместо списания) Тоже самое с заработком, балансом курьеров, количеством выполненных заказов, количества активаций промокода и тп
- слово rubles лучше избегать, так как сегодня мы с рублями, завтра с долларами. Лучше использовать абстрактные единицы. Давай заменим на value или что-то типа этого
- у промокода distibutor вводит в заблуждение. Давайте переименуем его в created_by_id?
- у техники нету срока годности, поэтому наверное expiration_date все же может иметь NULL
- supplier_check надо переименовать в supplier_invoice, как и is_check_paid (is_invoice_paid)
- у промокода при измении current_amount, нужен триггер, проверяющий на превышение лимитов активаций, первой активации или дат активации, и, соответственно, отключающий этот промокод
- Давайте picture сделаем более универсальным и превратим его в file? На будущее, вдруг захотим загружать еще и видео? А пока что текущий enum там оставим.
- У чата стоит date переименовать в created_date
- overall_price лучше переименовать в overall_cost
- Мне не хватило чеков размеров значений `CHECK(char_length())`. Например, чтобы пароль был больше 8 символов, имя человека было больше 5 символов, и тд. Да, мы будем проверять это все и на бэке, _но в случае чего_, чтобы был последний контур защиты от неправильного содержимого

2021-10-29 16:41 UTC, iLeonidze commented
@grey3228 

> Что мы храним в адресе курьера и нужен ли он?

Адрес где он проживает, чтобы понимать к какому ближайшему складу его подключить, административная инфа.


> Будет ли ок, если дефолтный рейтинг у курьера или клиента будет равным NULL? Например, клиент не выставляет оценку курьеру и/или наоборот.

Да. У яндекса, например, тупо 5 по дефолту стоит, но это неправильно на мой взгляд.


> Добавил триггеры в message на text и picture_uuid. Тут не знаю, как будет лучше, поскольку за триггеры пока вообще не шарю, поэтому поправьте.

Там примерно понятно о чем речь, думаю Михаил разберется.


> Добавить ли в product_position дату изготовления?

Изначально ожидалось что срок годности считается от даты поставки (как правило это один-два дня с момента производства), но для точности можем добавить. У поставки практически все имеет одну дату производства (ну кроме техники или что-то с очень большим сроком годности), поэтому забивается она легко, да.


> Как храним географические координаты? Через FLOAT8[ ] или через геометрические типы: POINT для координат заказа и склада, CIRCLE для зоны доставки от склада?

Предлагаю обсудить с ребятами приватно как будет лучше. Хорошо и так и так, постгря имеет функции для работы с геометрией, но вы можете и на бэке все вычисления делать.


> Как быть с товарами в отменённом заказе?

Должны возвращаться обратно


> Моя идея по поводу вопроса @swenkal об отменённом заказе и связанных товарах, если я правильно его понял: заказ отменяется, переводится в статус "cancelled", далее, по идее, срабатывает триггер, который все ассоциированные с заказом product_position'ы из order_product_position возвращает обратно в отменённом количестве в поле current_amount в таблицу product_position (опять же, я хз, может ли триггер такое провернуть, объясните, плз)
upd: посмотрел документацию, по идее, можно сделать цепочку триггеров по апдейту на конкретных столбцах таблиц "order -> order_product_position -> product_position".

Триггер может провернуть, также точно и через java-код сделать.

2021-10-29 16:43 UTC, iLeonidze commented
@swenkal 

> overall_price : тип MONEY + я не понял это стоимость уже с учетом всех скидок и надбавок за повышенный спрос??

Это финальная стоимость, которую оплатил/оплатит клиент

2021-10-30 16:07 UTC, grey3228 commented
Внёс изменения, запрошенные @iLeonidze. 
Координаты теперь хранятся в геометрических типах, как и предлагал @swenkal, ибо фактической разницы между ними и FLOAT[ ] нет, а семантически POINT и CIRCLE лучше, но если кто-то будет против, то я поправлю. 

Также относительно проверки по длине пароля: длина пароля в таблице для любого юзера всегда одна, т.к. BYTEA - массив из 32 байт (выхлоп SHA256). Конечно, можно сделать триггер, который будет после insert проверять длину ещё незахэшированного пароля и в случае малой длины кидать исключение, в противном случае делать sha256( ) и апдейтить поле. Но не знаю, насколько это безопасно. Возможно, лучше будет на бэке делать проверку на длину сразу и в таблицу помещать готовый хэш.

2021-11-01 08:54 UTC, iLeonidze commented
> Также относительно проверки по длине пароля: длина пароля в таблице для любого юзера всегда одна, т.к. BYTEA - массив из 32 байт (выхлоп SHA256). Конечно, можно сделать триггер, который будет после insert проверять длину ещё незахэшированного пароля и в случае малой длины кидать исключение, в противном случае делать sha256( ) и апдейтить поле. Но не знаю, насколько это безопасно. Возможно, лучше будет на бэке делать проверку на длину сразу и в таблицу помещать готовый хэш.

Небезопасно, обойдемся проверкой на бэке.

2021-11-01 08:56 UTC, iLeonidze approved these changes

2021-11-01 11:34 UTC, swenkal approved these changes
В целом замечания устранены, спасибо за работу @grey3228

2021-11-01 19:21 UTC, merged