Complete orders endpoints
iLeonidze/ncedu-food-delivery pull request #15
Opened 2021-12-19 01:55 UTC by grey3228

2022-01-11 15:23 UTC, swenkal commented
@grey3228 точно нужно ревью? PR пока в статусе "draft".

2022-02-03 22:23 UTC, grey3228 commented
В ходе рефакторинга решил, что лучше сразу заменю свой класс _Geo_ на копипаст класса @swenkal _CoordsDTO_, чтобы потом на этапе разрешения конфликтов при мердже не париться (если я всё учёл, хэх), так что @swenkal, не серчай :D

2022-02-04 16:43 UTC, swenkal requested changes
На 04.02.2022 посмотрел 39 файлов в ближайшие дни доберусь до остального, но уже сейчас как по мне есть что исправить.

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/controllers/OrderController.java
> +                                                               @PathVariable @Min(value = 1) @Max(value = Long.MAX_VALUE) Long id,
Хотел бы поделиться крутой штукой.  Spring может сразу искать необходимую нам сущность. Мы все также указываем при запросе на backend ID - но Spring автоматически возьмет на основе этого ID сущность которую мы укажем в PathVariable. Если он не найдет сущность - то плюнет ошибку MissingPathVariableException, которую я уже в GlobalExceptionHandler ловлю! 
```suggestion
    @GetMapping("/api/v1/user/{user}/orders")
    public ResponseEntity<List<OrderInfoDTO>> getOrdersHistory(@AuthenticationPrincipal User authedUser,
                                                               @PathVariable User user,
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/controllers/OrderController.java
> +    @GetMapping("/api/v1/user/orders")
У нас же есть отдельная ветка для профиля клиента (даже ProfileController есть!)
```suggestion
    @GetMapping("/api/v1/profile/orders")
```

Еще в раней версии у тебя была проверка на Роль админа и модератора этот момент можно решить как раз через `@PreAuthorize("hasAnyAuthority('COURIER', 'CLIENT')")`

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/controllers/OrderController.java
> +    @PreAuthorize("isAuthenticated()")
В принципе `@PreAuthorize("isAuthenticated()")` нам уже не нужен! Так как пользователь проверяется в фильтре JwtRequestFilter, только несколько путей общедоступны - на другие уже не пропустит, если не будет авторизован.

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/controllers/OrderController.java
> +    @GetMapping("/api/v1/order/{id}")
Как писал на строке 40-42 о касте сразу в сущность. Здесь и дальше (83, 93, 101, 111 строчки) я бы заменил на `@PatchMapping("/api/v1/order/{order}/status")`

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/dto/order/CountOrderCostResponseDTO.java
> +
У lombok есть крутая аннотация.
```suggestion
@AllArgsConstructor
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/dto/order/CountOrderCostResponseDTO.java
> +    }
Если вставишь аннотацию из коммента выше.
```suggestion
    public CountOrderCostResponseDTO() { }
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/dto/order/CreateOrderDTO.java
> +
Аналогично с `CountOrderCostResponseDTO `
```suggestion
   @AllArgsConstructor
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/dto/order/CreateOrderDTO.java
> +    }
```suggestion
    public CreateOrderDTO() {}
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/entities/order/Order.java
> +    public Order(Long id, Client client, String address, Geometry coordinates, Warehouse warehouse, Courier courier, OrderStatus status, Timestamp dateStart, Timestamp dateEnd, Double overallCost, Do
Попробовать `@AllArgsConstructor` после `@Data`

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/errors/GlobalExceptionHandler.java
> +    }*/
Нам точно нужен законченный handler в main?
```suggestion
  
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/errors/orderRegistration/OrderCostChangedEx.java
> +         super(String.format(Locale.US, "%s: currentOverallCost=%.2f,currentDiscount=%.2f,currentHighDemandCoeff=%.2f", OrderCostChangedEx.msg, currentOverallCost, currentDiscount, currentHighDemandC
При таком подходе теряется смысл наших кастомных ошибок или может быть не догоняю что-то под вечер.
Мы делаем ошибки с уникальными ID и довольно обтекаемыми описаниями (типа того, что у тебя в `msg`) для того, чтобы потом front мог у себя их локализовать, по-моему. А данное сообщение будет тяжело локализовать.

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/errors/security/UserLockedException.java
> +}
Вообще я в своем PR #20 реализовываю проверку блокировки на уровне фильтра, поэтому это думаю не нужно.

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/errors/wrappers/ProductNotEnoughSubError.java
> +    public static final String msg = "Not enough product in warehouse currently.";
SubError'ам вроде как не нужны UUID и MSG. У тебя они будут хранится в родительском классе ошибки
```suggestion

```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/errors/wrappers/ProductNotFoundSubError.java
> +public class ProductNotFoundSubError extends ApiSubError{
В целом не понял пока зачем нужен данный класс?

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/entities/User.java
> +
Сюда еще setter нужно запихнуть немного кастомный, чтобы работало создание объекта User и Courier/Moderator/Client просто через сущность User (я рассказывал эту проблему на позапрошлом митинге кажется).
 ```suggestion
public void setCourier(Courier courier) {
        this.courier = courier;
        this.courier.setUser(this);
    }
```

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/CourierRepo.java
> +public interface CourierRepo extends JpaRepository<Courier, Long> {
Ко всему РЕПО.
А может юзать Алиасы к таблицам, а не полное название? 
Это конечно, наверное, дело вкуса. @iLeonidze что по best practices?

2022-02-04 16:43 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/CourierRepo.java
> +                "(SELECT courier_id FROM orders WHERE courier_id IS NOT NULL) " +
Вот этот момент ломает мне голову! Не могу допереть, нужно пояснение @grey3228. 
Как я эти строчки понимаю:
как будто бы если курьер хотя бы раз В ИСТОРИИ ПРИЛОЖЕНИЯ уже доставлял заказ то он выберется в SELECT запросе, то есть в результате мы хотим получить ID только тех курьеров, которые еще ни разу не доставляли заказ? 
Мне кажется, просто на сегодня мое ревью подошло к концу....

2022-02-06 12:59 UTC, grey3228 commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/CourierRepo.java
> +                "(SELECT courier_id FROM orders WHERE courier_id IS NOT NULL) " +
В строках с 37 по 40 выбираются курьеры, которые привязаны к текущему складу и уже вышли на линию, но ещё никогда ничего не доставляли. Т.е. это для совсем новых курьеров идёт выборка.

2022-02-06 14:12 UTC, grey3228 commented
1. Спасибо, @swenkal , за подсказ с _@PathVariable_ - полезная вещь, сокращает кол-во написанного кода. Сделал, как ты показал, ну и тесты соответственно подправил для этого;
2. Осознал, что метод CourierRepo '_getAnotherAvailableCourier_' написан неправильно и не нужен, т.к. уже и так есть метод '_getWaitingCourierByWarehouse_' - он делает всё, как надо;
3. Сделал на методе '_getMyOrdersHistory_' разделение доступа через _@PreAuthorize('CLIENT', 'COURIER')_. До этого было '_isAuthenticated()_', поэтому любой юзер проваливался на уровень сервиса, где уже могло выбрасываться кастомное исключение _IncorrectUserRoleRequestException_ ;
4. Убрал везде в контроллере _@PreAuthorize('isAuthenticated()')_;
5. Изменил в контроллере в эндпоинтах '{orderId}' -> '{order}' в связи с п.1;
6. Использовал аннотацию _@AllArgsConstructor_;
7. Исправил исключение _OrderCostChangedEx_, добавил _OrderCostChangedSubError_ (см. далее); 
8. Удалил _UserLockedException_, т.к. @swenkal  взял это на себя в jwt.

Про _OrderCostChangedEx_. В принципе, локализовать в таком виде сообщение об ошибке можно, хоть это и не так просто, как с остальными. Нужно будет лишь на фронте распарсить эту строку, чтобы достать 3 значения и сделать подстановку. Но да, можно сделать и по-другому, поэтому сделал вариант с новым _ApiSubError_ - _OrderCostChangedSubError_, в который помещаются итоговая цена, скидка и коэффициент повышенного спроса. Соответственно, само сообщение об ошибке упростилось.

Про подошибку _ProductNotFoundSubError_. _ProductNotFoundSubError_ я задумывал на случай, когда пока клиент затаривается, из базы по какой-либо причине удаляют любую информацию о товаре из корзины  или о всех поставках товара из корзины. Вероятность такого события, конечно, очень низка. В принципе, ничего против не имею, можно и без этой подошибки обойтись.

2022-02-08 18:25 UTC, iLeonidze approved these changes

2022-02-10 16:32 UTC, swenkal reviewed
Есть некоторые  некритичные замечания, но можно выполнить уже в рамках другого PR

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/CourierRepo.java
> +                "(SELECT courier_id FROM orders WHERE courier_id IS NOT NULL) " +
Все равно не понял зачем это делается, по ощущениям это лишнее. Я поигрался немного с постгресом и мне кажется, что запроса ниже будет достаточно. 
`SELECT courier_id
FROM couriers 
INNER JOIN delivery_sessions USING (courier_id)  
WHERE delivery_sessions.end_time IS NULL 
    AND couriers.warehouse_id = 1 
    AND couriers.courier_id NOT IN  
        (SELECT courier_id FROM orders  
        WHERE orders.status IN ('COURIER_APPOINTED', 'PACKING', 'DELIVERING'))
LIMIT 1;`

Можешь прогнать его и потестить будет ли работать на твоих данных в тестовой БД?

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/dto/order/OrderInfoDTO.java
> +                    courier.getPhoneNumber(), courier.getRating(), courier.getWarehouse().getId(),
Вот здесь `courier.getWarehouse().getId()` ловлю ошибку NullPointerException!
А словил ее очень просто, хотел получить историю заказов для клиента (id = 2). Один из курьеров, который доставлял ему заказ у меня был заблокирован, когда курьера блокируют - у него обнуляется id склада. Соответственно у курьера Warehouse может быть null, а там уже сам понимаешь... 
Нужно что-то типа
```suggestion
                    courier.getPhoneNumber(), courier.getRating(), courier.getWarehouse() != null ? courier.getWarehouse.getId() : null,
```

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +    public List<OrderInfoDTO> getOrdersHistory(User authedUser, User targetUser, Pageable pageable) {
Просто задумался, а все заказы с определенного склада как получить? В рамках данного PR это, думаю лишнее, но вообще неплохо бы иметь такой метод.

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +            if(overallAmount < requestedAmount){
Если товарных позиций не хватает, то зачем дальше то считать стоимость запрошенного пользователем количества? 
Если позиций не хватает, то к следующему товару идем через continue;

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +            Product product = productRepo.findById(productId).get();
Зачем идти в репо, когда продукт у тебя под рукой. Если нам хватает позиций, то по-любому как минимум одна позиция в листе должна быть, следовательно:
```suggestion
            Product product = productPositions.get(0).getProduct();
```

2022-02-10 16:32 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +    public CountOrderCostResponseDTO countOrderCost(CountOrderCostRequestDTO dto) {
Долго высматривал чем отличается от этого метода  
`public Double[] countOrderCost(CoordsDTO geo,
                                    HashMap<Long, Integer> pairs, Long clientWarehouseId)`
 Видел, что только методы для получения продуктовых позиций разные в одном случае с локом, в другом без. 
 В остальном один в один все повторяется. Как нибудь это отрефакторить, но уже в рамках другого PR. по сути метода можно два оставить, но чтобы одни и те же функции использовали, например.

2022-02-10 19:37 UTC, grey3228 commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +    public List<OrderInfoDTO> getOrdersHistory(User authedUser, User targetUser, Pageable pageable) {
По идее, можно воспользоваться поиском с фильтрацией по параметрам запроса, такой метод есть

2022-02-11 08:45 UTC, swenkal approved these changes

2022-02-12 12:18 UTC, merged