About endpoint
iLeonidze/ncedu-food-delivery pull request #2
Opened 2021-10-29 14:12 UTC by swenkal

Когда ветка только создавалась она была для endpoint whoami. Но уже все быстро поменялось, поэтому endpoint сменил свое название, а ветка не успела. 
Сделал контроллер About, в нем определил endpoint "/api/v1/about", который создает объект AboutDTO (хранит структуру, которая будет сконвертирована в JSON). 
С помощью сервиса TestDbConnect получаем имя БД, к которой подключились. Имя БД кладём в объект AboutDTO и отправляем в качестве ответа.

2021-10-29 15:46 UTC, iLeonidze requested changes

2021-10-29 15:46 UTC, iLeonidze commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
А нам точно надо все содержимое .mvn?
Такое ощущение что ты забыл добавить его в эксклюд

2021-10-29 15:46 UTC, iLeonidze commented on README.md
> +- installed PostgreSQL in Docker container (with user postgres/postgres)
Добавь линку на имадж на докерхабе + пример как делать docker run

2021-10-29 15:46 UTC, iLeonidze commented on README.md
> +      ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=<DOCKER_IMAGE_NAME>
Предлагаю вместо `<DOCKER_IMAGE_NAME>` использовать прямо захардкоженное имя имаджа и контейнера, так как никакого секрета в его наименовании нет и у проекта и так есть его название

2021-10-29 15:46 UTC, iLeonidze commented on README.md
> +- work with food-delivery API on http://{YOUR_IP_OR_HOST}:8080
Проверь, должно работать на 127.0.0.1 вместо `{YOUR_IP_OR_HOST}`

2021-10-29 15:46 UTC, iLeonidze commented on pom.xml
> +	<description>Educational project</description>
```suggestion
	<description>Service for ordering products and household goods at home from local warehouses</description>
```

2021-10-29 15:46 UTC, iLeonidze commented on src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.postgresql.Driver
Давай сделаем тут инит дб по доке https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization

Нужно докинуть сюда пару конфигов что-то в духе
```
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.schema-locations=classpath*:database/initDB.sql
spring.sql.init.data-locations=classpath*:database/pushData.sql
```
Ну и сами скрипты создания таблиц и заполнения данным создай, но пустые

2021-10-30 07:07 UTC, swenkal commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
Это wrapper, который позволяет делать Docker image сразу из под Maven. Я могу убрать, если это не нужно.

2021-10-30 07:08 UTC, swenkal commented on README.md
> +- installed PostgreSQL in Docker container (with user postgres/postgres)
Ссылку на имадж postgre? или залить туда свой имадж с нашим приложением?

2021-10-30 07:09 UTC, swenkal commented on README.md
> +      ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=<DOCKER_IMAGE_NAME>
хорошо

2021-11-01 08:52 UTC, iLeonidze requested changes
По таблицам и прочему все ок, остались только вопросы со сборкой.

2021-11-01 08:52 UTC, iLeonidze commented on Dockerfile
> +WORKDIR application
Давай положим все в /opt/app

2021-11-01 08:52 UTC, iLeonidze commented on Dockerfile
> +FROM adoptopenjdk:14-jre-hotspot as builder
Чем [openjdk](https://hub.docker.com/_/openjdk) не устроил?

2021-11-01 08:52 UTC, iLeonidze commented on Dockerfile
> +COPY ${JAR_FILE} application.jar
Совсем не понял зачем здесь копируется из target/*. До того, как ты собрал что либо - там ничего нет и не будет - вся сборка должна быть внутри контейнера.

2021-11-01 08:52 UTC, iLeonidze commented on Dockerfile
> +FROM adoptopenjdk:14-jre-hotspot
Стоит в этот контейнер добавить пользователя с обычными правами
```
RUN groupadd -r anonymous && useradd -r -g anonymous anonymous
RUN chown anonymous -R /opt/app && chmod 700 -R /opt/app
```

2021-11-01 08:52 UTC, iLeonidze commented on README.md
> +- build project with Maven (must create 'target' folder):
Да, тут нарушается самая идея докеримаджей - вся сборка должна быть исключительно в них происходить, а тут у тебя сначала что-то собирается на хосте. Представь, если бы мы собирали не джарку, а C++ апп - там бы была компиляция с биндами к либам операционной системы, и собрав на макоси и засунув бинарь в докерфайл мы бы получили нерабочий докерфайл)

Почему нарушается принцип сборке через докеримаджи - потому что исходная сборка аппа собирается в окружении с неизвестными переменными - мы не знаем на какой оси, с какими либами секьюрити собиралось, не знаем даже версию джавы. Сборка внутри контейнера дает гарантию знания в каком окружении и как все собиралось, минимизируя вектор проблем с окружением.

2021-11-12 17:12 UTC, grey3228 commented on README.md
> +docker run --name pg-delivery -e POSTGRES_PASSWORD=postgres -d postgres
В этой строке я бы ещё явно добавил опцию, указывающую связь между портами контейнера и хоста, т.к. у меня иначе при сборке имаджа на этапе тестов валится исключение. Крч, я бы эту строчку так сделал: "docker run --name pg-delivery -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres"

2021-11-12 18:00 UTC, grey3228 commented on README.md
> +docker run --name pg-delivery -e POSTGRES_PASSWORD=postgres -d postgres
```suggestion
docker run --name pg-delivery -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres
```

2021-11-12 18:10 UTC, grey3228 approved these changes

2021-11-16 14:22 UTC, iLeonidze commented on README.md
> +- installed PostgreSQL in Docker container (with user postgres/postgres)
Первое

2021-11-16 14:23 UTC, iLeonidze commented on README.md
> +- installed PostgreSQL in Docker container (with user postgres/postgres)
Но наверное уже не очень актуально, так как в доке есть инструкция по старту самого имаджа

2021-11-16 14:25 UTC, iLeonidze approved these changes

2021-11-16 14:25 UTC, merged