React delivery sessions
iLeonidze/ncedu-food-delivery pull request #26
Opened 2022-03-25 20:53 UTC by grey3228

2022-03-26 22:01 UTC, grey3228 commented
В рамках данного PR реализуются функции, доступные курьеру - просмотр истории заказов, выход на линию и завершение выхода на линию, 
Добавлен хук useProfile для установки профиля юзера при входе, чтобы гибко выстраивать маршрутизацию: часть маршрутов будет отображена только для юзеров с ролью "курьер".
Добавлены компоненты:
- _History_ - просмотр истории заказов с пагинацией;
- _HistoryCard_ - карточки заказов, которые отображаются в компоненте _History_;
- _SessionDetails_ - страница для просмотра информации о конкретном выходе на линию, включая доставленные за заказы, общую информацию о выходе на линию: прибыль, время начала и завершения (если выход завершён). Если курьер выходит на линию (с помощью кнопки в этом компоненте), то начинается опрос бэкенда с целью поиска заказа. 
Для взаимодействия с API бэкенда реализован класс _DeliverySessionClient_. На стороне бэкенда дополнительно реализован метод _getAmount(User u)_ для пагинации.
Также в _OrderClient_ добавлены методы для получения текущего заказа _getCurrentOrder(User u)_ и метод для получения заказов из текущего выхода на линию _getOrdersFromDeliverySession(User u, DeliverySession deliverySession)_.

2022-03-31 18:00 UTC, swenkal requested changes
Я уже хотел апрувать, но мне кажется ошибка в OrderServiseImpl1 критичной, думаю исправить ее не составит труда!

2022-03-31 18:00 UTC, swenkal commented on front/src/App.js
> +  const { profile, setProfile } = useProfile();
Хук useProfile скорее всего лишний, так как роль пользователя можно посмотреть через auth.token.user.role.
Поэтому нужно пересмотреть данный момент.

2022-03-31 18:00 UTC, swenkal commented on front/src/components/deliverySessionComponents/SessionDetails.js
> +            </Typography.Text></div>
В react подглядел такую штуку как разыменование вложенных сущностей у компонента.
каждый раз писать `Typography.Text` застрелиться можно!
Вверху после импорта можно получить необходимые дочерние компоненты. 
Пример для "Text":
`const { Text } = Typography;` и дальше в коде уже юзаем просто `<Text></Text>`

2022-03-31 18:00 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/controllers/OrderController.java
> +                HttpStatus.OK);
Не пойму что здесь происходит? Зачем два раза вызываем сервис `orderService.getCurrentOrder(user)` ?
Мы записали результат первого вызова в `orderInfoDTO` если null, то нет контента, а если есть, то посылаем уже полученное DTO ,  или я что-то упускаю?

2022-03-31 18:00 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +        return orderRepo.getOrdersByCourierId(courier.getId()).stream()
Может быть и вкусовщина и я слишком придираюсь, но не лучше ли на уровне запроса отфильтровать и отсортировать заказы курьера по сессии?
Ведь мы все заказы курьера грузим в память из БД! Это сейчас на тестовых данных у нас не много заказов у курьера, а так в будущем и 1000 и 10000 может быть и все они в память попадут, нехорошо, думаю.

2022-04-02 11:03 UTC, swenkal requested changes
Еще совсем чуть чуть и будет просто конфетка !!!! 
@grey3228 дело нескольких минут, все заправлю после этого исправления

2022-04-02 11:03 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/order/OrderRepo.java
> +                   nativeQuery = true)
Мне кажется, что ты перемудрил. Можно же в функцию, если endTime == null, передавать LocalDateTime.now() и тогда все схлопнется в удобоваримую конструкцию!
```suggestion
    @Query(value = "SELECT * FROM orders " +
                   "WHERE courier_id = :courierId AND " +
                   "      date_start >= :startTime " +
                   "      AND date_start <= :endTime",
                   nativeQuery = true)
```

2022-04-02 11:03 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +        System.out.println(deliverySession.getEndTime());
```suggestion
        LocalDateTime endTime = deliverySession.getEndTime() == null ? LocalDateTime.now() : deliverySession.getEndTime();
```

2022-04-02 11:03 UTC, swenkal commented on src/main/java/com/ncedu/fooddelivery/api/v1/services/impls/OrderServiceImpl1.java
> +                deliverySession.getEndTime())
```suggestion
                endTime)
```

2022-04-02 11:39 UTC, grey3228 commented on src/main/java/com/ncedu/fooddelivery/api/v1/repos/order/OrderRepo.java
> +                   nativeQuery = true)
Супер, я просто не додумался :/

2022-04-02 12:20 UTC, merged