Changing table names, price types and resolving other problems
iLeonidze/ncedu-food-delivery pull request #3
Opened 2021-11-06 17:42 UTC by grey3228

Изменены названия таблиц (от единственного числа перешли но множественное), исправлены некоторые опечатки в полях таблиц, добавлены check'и на номера телефонов, триггер на деактивацию склада, изменён тип поля price с MONEY на NUMERIC(12, 2). Внешние ключи теперь имеют тип не BIGSERIAL, а BIGINT. Так же в целях избежания тавтологии, убрал NOT NULL у примарных ключей.
@iLeonidze , @swenkal , MONEY повсеместно менял на NUMERIC(12, 2), поэтому, например, у курьера заработок за выход на линию может достигнуть 10 миллиардов :D Поэтому давайте определим, сколько сможет заработать курьер. То же касается и discount, discount_value.

2021-11-09 18:37 UTC, swenkal requested changes
Я заметил некоторые неточности. Все по большей части пустячные, но предлагаю все-таки исправить.

**PROMO_CODES**

1. CHECK для date_start и date_end. Заметил у тебя, что ты на UML схеме делаешь только сравнение по разницам дней даты. Но ведь промокоды могут и не один месяц действовать. Кейс: date_start='10.10.2021', date_end='08.10.2021'. day(end) - day(start) < 0, но по факту то все правильно. Дата окончания позже даты старта действия.
Заменить на просто ЧЕК (постгря так может): 
**CHECK(date_end > date_start)** 

2. usr_id -> user_id 

**FILES и везде, где есть FK на эту таблицу**
для PK таблицы(ТБ) FILES имя - uuid (которое, вроде как зарезервировано). и во всех остальных FK у нас приставка не "id", а "uuid". Мне кажется она излишней, предлагаю ее изменить.  То есть:
1. Таблица(ТБ) FILES: file_id 
2. ТБ USERS: avatar_id
3. ТБ PRODUCTS: picture_id
4. ТБ MESSAGES: picture_id. 
Прошу @iLeonidze  подсказать есть ли в этом смысл, или uuid лучше оставить?

**ORDERS**

В качестве FK для того, кто заказывает указан "user_id", хотя заказ то делает пользователь с ролью 'client'. То есть, если оставляем FK на "user_id", то, по-хорошему, нужно CHECK делать на то, есть ли user с таким id в ТБ CLIENTS. Потому что только в ТБ CLIENTS есть payment_data, которую мы должны постоянно обновлять.
Поэтому с user_id -> client_id (соответсвенно стрелочку тоже от ТБ CLIENTS к ORDERS).

Две придирки по названию (можем оставить как есть, просто давайте обсуждать)
**CHATS**: created_date -> create_date
**MESSAGES**: date -> send_date

2021-11-13 12:09 UTC, grey3228 commented
В последнем коммите я учёл почти все замечания @swenkal, за исключением изменения названий столбцов, содержащих ссылку/само UUID, т.е. менять "uuid" на "id" в названиях. В принципе, я смог создать таблицу со столбцом "uuid UUID" (соответственно, название столбца и его тип) и повставлять туда значения - проблем не было. Поэтому вопрос по этим названиям открыт, прошу @iLeonidze подсказать, как будет лучше. Кроме того, как мы договорились на прошлой встрече, максимальный доход курьера за 1 выход на линию - 100 000, так же как и цена заказа (если я ничего не путаю). В этой связи, вместо NUMERIC(12, 2) я вставил теперь NUMERIC(7, 2), т.е. максимально туда мы можем положить теперь  99 999.99 .

2021-11-16 14:27 UTC, iLeonidze approved these changes

2021-11-16 14:30 UTC, iLeonidze commented
Мне нравится uuid, так как сразу понятно что речь идет про уникальный объект в файловой системе, в то время как просто id ассоциируется с генерируемым объектом в таблице. Возможно, приписка uuid поможет, в кейсах когда будете обрабатывать работу с удалением записей из таблицы, и вспомните что у uuid нужно будет не забыть и в самой fs удалить файл

2021-11-16 14:30 UTC, merged