Adding my part of sql scripts and correcting .properties
iLeonidze/ncedu-food-delivery pull request #5
Opened 2021-11-19 15:58 UTC by grey3228

Сделал все свои таблички. Сразу скажу, что insert'ы в таблицу delivery_sessions можно было придумать и интереснее (на данный момент, в каждой сессии только 1 заказ, т.е. курьеры будто после каждого выполненного заказа прекращали сессию, а потом стартовали новую), но у меня в заказах даты заданы не статически, а определяются динамически (через CURRENT_DATE и т.д.). Поэтому, чтобы долго не возиться, сделал пока так. Но в дальнейшем нам ничто не помешает руками в случае необходимости несколько таких сессий накидать.
Конфиг правил так в соответствии с тем, что мы договорились перейти на postGIS. @swenkal, если у тебя такой вариант не заработает, то будем менять, у меня всё ок.

2021-11-21 12:49 UTC, swenkal requested changes
Есть парочку моментов для уточнения, также есть предложения по исправлениям в properties и в одной из функций в schema.sql

2021-11-21 12:49 UTC, swenkal commented on README.md
> +docker run --name pg-delivery -p 5432:5432 -e POSTGRES_PASSWORD=postgis -e POSTGRES_USER=postgis -d postgis/postgis
В целом все равно, но все же интересно. Чем тебя имя БД, пользователя и пароля помешали то? :D

2021-11-21 12:49 UTC, swenkal commented on src/main/resources/initDB/schema.sql
> +                UPDATE product_positions orders_product_positions SET current_amount = current_amount + (SELECT amount FROM orders INNER JOIN orders_product_positions USING(order_id) WHERE order_id =
Тут случайно нет ошибки? может нужно убрать **orders_product_positions** в начале ?  
```suggestion
                UPDATE product_positions SET current_amount = current_amount + (SELECT amount FROM orders INNER JOIN orders_product_positions USING(order_id) WHERE order_id = NEW.order_id AND product_position_id = pos) WHERE product_position_id = pos; 
```

2021-11-21 12:49 UTC, swenkal commented on src/main/resources/initDB/schema.sql
> +                                             product_id BIGINT NOT NULL,
Не увидел FOREIGN KEY для **product_id**

2021-11-21 12:49 UTC, swenkal commented on src/main/resources/application.properties
> +spring.sql.init.data-locations=classpath:/initDB/data.sql
Опытным путем пришел к таким пропертям для инициализации. Пока больше ни разу не валились у меня. Предлагаю их использовать. 
```suggestion
spring.datasource.schema=classpath:initDB/schema.sql
spring.datasource.data=classpath:initDB/data.sql
```

2021-12-02 16:18 UTC, grey3228 commented on README.md
> +docker run --name pg-delivery -p 5432:5432 -e POSTGRES_PASSWORD=postgis -e POSTGRES_USER=postgis -d postgis/postgis
Ахахах, да ничем, мне это ни в коем случае не принципиально) Просто когда менял readme, нужно было менять название образа с dockerhub (postgis/postgis), вот я заодно чёт всё остальное тоже поменял. Не вопрос, откачу имена бд и юзера, пароль обратно, чтобы привычнее выглядело

2021-12-02 16:38 UTC, grey3228 commented
Вместо оставления коммента по поводу комментария @swenkal (см. https://github.com/netcracker-edu/2021-msk-food-delivery/pull/5/commits/6a607ac357de8ad6399f0c4d8ba20d7c0f407331) прожал на принятие изменений :/

2021-12-02 17:14 UTC, grey3228 commented on src/main/resources/application.properties
> +spring.sql.init.data-locations=classpath:/initDB/data.sql
Такие свойства помечаются Deprecated. Мб всё же не использовать?

2021-12-03 07:35 UTC, swenkal approved these changes
Одна помарочка, но незначительная абсолютно.
Уже давно пора мерджить  данный PR и пробовать запуститься со всеми данными Миши и моими.

2021-12-03 07:35 UTC, swenkal commented on src/main/resources/application.properties
> +spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true
Затесалось из реализации уже product_positions!
в принципе, предлагаю оставить. Ничего криминального, потом все равно добавлять.

2021-12-09 13:11 UTC, iLeonidze approved these changes
Нужно поправить конфликты и последние вопросы от Александра, в остальном ок

2021-12-09 20:37 UTC, merged